version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo4
  web:
    build: .
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DBNAME=todo4
    depends_on:
      - db
volumes:
  data:
