const todos = [
  {
    title: "Todo 1",
    is_active: true,
    priority: "very-high",
    activity_group_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: "Todo 2",
    is_active: false,
    priority: "low",
    activity_group_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: "Todo 3",
    is_active: false,
    priority: "medium",
    activity_group_id: 3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: "Todo 4",
    is_active: false,
    priority: "very-high",
    activity_group_id: 4,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: "Todo 5",
    is_active: false,
    priority: "low",
    activity_group_id: 5,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: "Todo 6",
    is_active: true,
    priority: "medium",
    activity_group_id: 1,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: "Todo 7",
    is_active: true,
    priority: "very-high",
    activity_group_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: "Todo 8",
    is_active: true,
    priority: "low",
    activity_group_id: 3,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: "Todo 9",
    is_active: true,
    priority: "medium",
    activity_group_id: 6,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    title: "Todo 10",
    is_active: true,
    priority: "very-high",
    activity_group_id: 2,
    created_at: new Date(),
    updated_at: new Date(),
  },
];

module.exports = todos;
